### ISSUE TITLE
My skin face is not showing up with the discord bot

### ISSUE THREAD

**Issue by GustyCube** [MC-Linker/MC-Linker#56]

**Comment by Lianecx** [comment]
Are you using a bedrock account with geyser or do you have a cracked account?

**Comment by GustyCube** [comment]
I am using Java edition.

**Comment by Lianecx** [comment]
Can you dm your server id to “lianecx” on discord please so i can take a closer look at your problem?

**Comment by GustyCube** [comment]
Have to be friends to DM.

**Comment by GustyCube** [comment]
Now it works. Thank you anyway.

**Comment by Lianecx** [comment]
Okay if you have any more problems, feel free to let me know in the support discord server: https://discord.gg/https://discord.gg/rX36kZUGNK
