### ISSUE TITLE
Players can't join without linking MC to discord

### ISSUE THREAD

**Issue by TheEpicTen** [MC-Linker/MC-Linker#59]
We want users to be able to link their accounts, but we don't want them to have to. How can we disable this requirement?

**Comment by TheEpicTen** [comment]
Not using this plugin anymore.

**Comment by Lianecx** [comment]
![image](https://github.com/user-attachments/assets/8688f817-868c-4f8c-b443-5054212b85ff)
That's actually really easy to do, just set the join-requirement to "None" when you connect your server (its also the default)

Is there any other reason you decided to stop using this plugin? Mine telling me your alternative?
